### ISSUE TITLE
[BUG] Module:Grayfilter crashes when removing

### ISSUE THREAD

**Issue by D4wN** [Loremipsum1988/tinkervision#1]
Look at provided file --> [testFile.txt](https://github.com/Loremipsum1988/tinkervision/files/136124/testFile.txt)

Traceback (most recent call last):
  File "C:/Programmierung/Repos/Python/TinkervisionBrickv/TEST.py", line 220, in <module>
    doStuff(red);
  File "C:/Programmierung/Repos/Python/TinkervisionBrickv/TEST.py", line 18, in doStuff
    kill_all_modules(red)
  File "C:/Programmierung/Repos/Python/TinkervisionBrickv/TEST.py", line 67, in kill_all_modules
    print "KILL_ALL_MODULES = " + str(red.vision_remove_all_modules())
  File "C:\Programmierung\Repos\Python\TinkervisionBrickv\src\brickv\bindings\brick_red.py", line 1248, in vision_remove_all_modules
    return self.ipcon.send_request(self, BrickRED.FUNCTION_VISION_REMOVE_ALL_MODULES, (), '', 'h')
  File "C:\Programmierung\Repos\Python\TinkervisionBrickv\src\brickv\bindings\ip_connection.py", line 963, in send_request
    raise Error(Error.TIMEOUT, msg)
brickv.bindings.ip_connection.Error: Did not receive response for function 97 in time (-1)

**Comment by D4wN** [comment]
Added Log-Files ([tv.log](https://github.com/Loremipsum1988/tinkervision/files/142598/tv.txt) & [redapid.log](https://github.com/Loremipsum1988/tinkervision/files/142599/redapid.txt)). 
Last entrie in [redapid.log](https://github.com/Loremipsum1988/tinkervision/files/142599/redapid.txt) is:
_/usr/bin/redapid: symbol lookup error: /home/tf/tv/lib/grayfilter.so: undefined symbol: _ZN2cv11_InputArrayC1ERKNS_3MatE_

**Comment by D4wN** [comment]
Possibly fixed with updated Grayfilter.so
